[package]
name = "gc9a01a_driver"
version = "0.1.0"
edition = "2021"
authors = ["GordonCox"]
license = "MIT"
repository = "https://github.com/GordonCox/gc9a01a_driver.git"

[dependencies]
embedded-hal = { version = "0.2" }
embedded-graphics = { version = "0.8.1" }